name : Task Managment System

on: 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
    build:
      runs-on : ubuntu-latest
      steps: 
        - uses: actions/checkout@v4
        - name: Setup Dot Net
          uses : actions/setup-dotnet@v4
          with:
            dotnet-version: 8.x

        - name : Install Dependencies
          run :  dotnet restore ./TaskManagmentSystem/TaskManagmentSystem.csproj
        - name : Build
          run :  dotnet build ./TaskManagmentSystem/TaskManagmentSystem.csproj --configuration Release --no-restore

    terraform :
      runs-on : ubuntu-latest
      needs : build

      env: 
         ARM_CLIENT_ID : ${{ secrets.AZURE_CLIENT_ID }}
         ARM_CLIENT_SECRET : ${{ secrets.AZURE_CLIENT_SECRET }}
         ARM_SUBSCRIPTION_ID : ${{ secrets.AZURE_SUB_ID }}
         ARM_TENANT_ID : ${{ secrets.AZURE_TENANT_ID }}
      defaults:
         run:
            working-directory : ./TaskManagmentSystem/Infra/Terraform
      steps:
         - uses: actions/checkout@v4
  
         - name : SetUp Terraform
           uses: hashicorp/setup-terraform@v3

         - name : Terraform Init
           run : terraform init

         - name : Terraform Plan
           run : terraform plan
         
         - name : Terraform Apply
           if: github.event_name != 'pull_request'
           run : terraform apply -auto-approve

    publish :
       runs-on : ubuntu-latest
       needs : terraform
       if: github.event_name != 'pull_request'
       steps:
          - uses: actions/checkout@v4
          - name : Publish App
            run : dotnet publish ./TaskManagmentSystem/TaskManagmentSystem.csproj --tl:on --configuration Release --output ./Publish

          - name: Deploy
            uses: azure/webapps-deploy@v2
            with:
              app-name: taskmanagment-vk
              publish-profile: ${{ secrets.Azure_PublishWeb_Secret }}
              package: ./Publish
  